//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionItems
    {
        public long ActionItemId { get; set; }
        public string Description { get; set; }
        public System.DateTime DueDate { get; set; }
        public string PostActionUpdate { get; set; }
        public string EmployeeDocumentId { get; set; }
        public bool Completed { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
