//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentTestResults
    {
        public long AssessmentId { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public long QuestionId { get; set; }
        public float Score { get; set; }
        public string EmployeeDocumentId { get; set; }
        public float SelfScore { get; set; }
        public string SelfComments { get; set; }
    
        public virtual AssessmentTestQuestions AssessmentTestQuestions { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
