//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentTestResults
    {
        public long AssessmentId { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public long QuestionId { get; set; }
        public float Score { get; set; }
        public string EmployeeDocumentId { get; set; }
        public float SelfScore { get; set; }
        public string SelfComments { get; set; }
    
        public virtual AssessmentTestQuestions AssessmentTestQuestions { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
