//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentTestQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentTestQuestions()
        {
            this.AssessmentTestResults = new HashSet<AssessmentTestResults>();
        }
    
        public long QuestionId { get; set; }
        public string QuestionText { get; set; }
        public long CAndPId { get; set; }
    
        public virtual CompetencyAndPerformance CompetencyAndPerformance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTestResults> AssessmentTestResults { get; set; }
    }
}
