//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAndPByPP
    {
        public long PPId { get; set; }
        public long CoPId { get; set; }
        public int AchievementPorcentage { get; set; }
        public bool AssessmentCompleted { get; set; }
    
        public virtual CompetencyAndPerformance CompetencyAndPerformance { get; set; }
        public virtual PerformanceProfile PerformanceProfile { get; set; }
    }
}
