//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AssessmentTestResults = new HashSet<AssessmentTestResults>();
            this.PerformanceProfile = new HashSet<PerformanceProfile>();
        }
    
        public long CC { get; set; }
        public string FullName { get; set; }
        public int DeliveryUnitId { get; set; }
        public int GradeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTestResults> AssessmentTestResults { get; set; }
        public virtual DeliveryUnits DeliveryUnits { get; set; }
        public virtual Grades Grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceProfile> PerformanceProfile { get; set; }
    }
}
