//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ActionItems = new HashSet<ActionItems>();
            this.AssessmentTestResults = new HashSet<AssessmentTestResults>();
            this.Employee1 = new HashSet<Employee>();
            this.OportunitiesOfImprovement = new HashSet<OportunitiesOfImprovement>();
            this.PerformanceProfile = new HashSet<PerformanceProfile>();
            this.Strengths = new HashSet<Strengths>();
        }
    
        public string DocumentId { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DeliveryUnitId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string UserId { get; set; }
        public string LeadDocumentId { get; set; }
        public string PictureURL { get; set; }
        public Nullable<bool> IsLead { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionItems> ActionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTestResults> AssessmentTestResults { get; set; }
        public virtual DeliveryUnits DeliveryUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Grades Grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OportunitiesOfImprovement> OportunitiesOfImprovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceProfile> PerformanceProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Strengths> Strengths { get; set; }
    }
}
