//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KEPT_DBEntities : DbContext
    {
        public KEPT_DBEntities()
            : base("name=KEPT_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AssessmentTestQuestions> AssessmentTestQuestions { get; set; }
        public virtual DbSet<AssessmentTestResults> AssessmentTestResults { get; set; }
        public virtual DbSet<CAndPByPP> CAndPByPP { get; set; }
        public virtual DbSet<CompetencyAndPerformance> CompetencyAndPerformance { get; set; }
        public virtual DbSet<DeliveryUnits> DeliveryUnits { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<OportunitiesOfImprovement> OportunitiesOfImprovement { get; set; }
        public virtual DbSet<PerformanceProfile> PerformanceProfile { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<SkillsByPP> SkillsByPP { get; set; }
        public virtual DbSet<Strengths> Strengths { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trainnings> Trainnings { get; set; }
        public virtual DbSet<TrainningsByPP> TrainningsByPP { get; set; }
        public virtual DbSet<ActionItems> ActionItems { get; set; }
    }
}
