//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunitiesOfImprovement
    {
        public long OOIId { get; set; }
        public long CAndPId { get; set; }
        public string Description { get; set; }
        public bool Completed { get; set; }
        public System.DateTime GoalDate { get; set; }
    
        public virtual CompetencyAndPerformance CompetencyAndPerformance { get; set; }
    }
}
