//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeptWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillsByPP
    {
        public int SkillId { get; set; }
        public long PPId { get; set; }
        public string Description { get; set; }
    
        public virtual PerformanceProfile PerformanceProfile { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
